const firstp = document.getElementById("firstoption")
const secondp = document.getElementById("secondoption")

const div1 = document.getElementById("firstcontent")
const div2 = document.getElementById("secondcontent")

const firstnum = document.getElementById("firstnum")
const secondnum = document.getElementById("secondnum")

let redpicked = 0
let bluepicked = 0

const questions = {
    first: [
        "Have the ability to fly",
        "Live without the internet",
        "Be able to talk to animals",
        "Have unlimited money but no friends",
        "Always know when someone is lying",
        "Be famous but poor",
        "Have super strength",
        "Be the smartest person in the world",
        "Travel to the past",
        "Have a rewind button for your life",
        "Only eat pizza forever",
        "Be stuck on an island alone",
        "Win the lottery but lose all your friends",
        "Be able to teleport anywhere",
        "Have the ability to stop time",
        "Be constantly itchy",
        "Be feared by all",
        "Be able to read minds",
        "Have a personal chef",
        "Never have to sleep",
        "Control fire",
        "Be a superhero with a silly costume",
        "Live in space",
        "Have infinite energy",
        "Speak all languages",
        "Be the best athlete in the world",
        "Own a private island",
        "Be invisible at will",
        "Only be able to whisper",
        "Be a famous actor",
        "Have no taste buds",
        "Be able to control the weather",
        "Have a robot best friend",
        "Be 10 years older",
        "Always have to sing instead of talk",
        "Have a pet dinosaur",
        "Never age",
        "Have teleportation powers",
        "Only be able to wear clown clothes",
        "Be extremely lucky",
        "Be able to pause movies with your mind",
        "Live in a world with zombies",
        "Have laser eyes",
        "Be able to clone yourself",
        "Have the best singing voice",
        "Own a time machine that only goes forward",
        "Be rich but never travel",
        "Live underwater",
        "Have super speed",
        "Be able to breathe underwater",
        "Have a flying car",
        "Always be 5 minutes early",
        "Be the fastest runner in the world",
        "Have perfect memory",
        "Be able to grow any plant instantly",
        "Be able to turn invisible once a day",
        "Always have perfect weather wherever you go",
        "Be able to talk to ghosts",
        "Live in a castle",
        "Have a jetpack",
        "Be the world's best chef",
        "Have unlimited free clothes",
        "Be able to control dreams",
        "Have a pocket that holds anything",
        "Have night vision",
        "Have a magic carpet",
        "Always win at rock, paper, scissors",
        "Be able to change your eye color at will",
        "Have a hoverboard",
        "Be able to make objects levitate",
        "Live on a luxury cruise forever",
        "Have a magic mirror that answers questions",
        "Be able to erase embarrassing memories",
        "Have your own amusement park",
        "Always have the newest phone",
        "Be able to jump super high",
        "Have a loyal talking dog",
        "Be able to create fireballs",
        "Be the best video gamer in the world",
        "Have hair that changes color with your mood",
        "Be able to shrink down to ant size",
        "Be a world-class artist",
        "Have unlimited popcorn",
        "Be able to sleep instantly at any time",
        "Have a personal masseuse",
        "Have rainbow-colored eyes",
        "Have shoes that let you walk on walls",
        "Be able to turn into any animal",
        "Have a never-ending backpack of snacks",
        "Have the ability to swap voices with anyone",
        "Live in a candy house",
        "Have a snowball that never melts",
        "Be able to play any instrument perfectly",
        "Have a car that drives itself",
        "Have your own private rollercoaster",
        "Be able to teleport but only once a day",
        "Have sunglasses that see through walls",
        "Always win at claw machines",
        "Have pillows that make you dream whatever you want",
        "Be able to rewind any TV show or movie in real life",
        "Have glitter hair",
        "Have a giant robot friend",
        "Have an unlimited supply of ice cream",
        "Have a remote that pauses the world for 5 minutes",
        "Have candy that changes flavor every bite",
        "Have hands that can freeze things",
        "Have a tail like a monkey",
        "Have a scooter that goes as fast as a car",
        "Have socks that never get dirty",
        "Be able to walk on clouds",
        "Have a bed that flies",
        "Have a hoodie that changes color",
        "Have a phone that never dies",
        "Have a watch that stops time for 10 seconds",
        "Have a skateboard that hovers",
        "Have hair that grows into cool styles overnight",
        "Have a pet unicorn",
        "Have the ability to glow in the dark",
        "Have pockets that generate money once a day",
        "Have glasses that translate any language",
        "Have a fridge that refills itself",
        "Have shoes that make you jump 10 meters high",
        "Have a flashlight that shows the future",
        "Have a pillow that makes you feel fully rested in 5 minutes",
        "Have music follow you everywhere",
        "Have a blanket that makes you invisible",
        "Have a ring that lets you breathe in space",
        "Have slippers that make you float",
        "Have a wallet that gives you candy every hour",
        "Have a jacket that always keeps you at perfect temperature",
        "Have a camera that takes pictures of your dreams",
        "Have gloves that can catch anything",
        "Have a hat that changes into any hat you imagine",
        "Have a talking cat",
        "Have a bike that never gets flat tires",
        "Have a house that cleans itself",
        "Have a backpack that holds infinite items",
        "Have toothpaste that makes your breath smell like chocolate",
        "Have glasses that show people's thoughts as emojis",
        "Have headphones that play your favorite song anytime",
        "Have a balloon that floats forever",
        "Have a pen that draws anything into reality",
        "Have a couch that massages you",
        "Have a watch that tells the weather perfectly",
        "Have a book that writes stories about your day",
        "Have a hoodie that makes you invisible at night",
        "Have ice cream that never melts",
        "Have a pet dragonfly the size of a cat",
        "Have a mirror that changes your hairstyle every day"
    ],
    second: [
        "Be invisible",
        "Live without your phone",
        "Speak all human languages fluently",
        "Have lots of friends but no money",
        "Always get away with lying",
        "Be rich but unknown",
        "Have super intelligence",
        "Be the most charming person in the world",
        "Travel to the future",
        "Have a fast-forward button for your life",
        "Only eat burgers forever",
        "Be stuck on an island with someone you hate",
        "Win the lottery but never enjoy the money",
        "Have the ability to fly",
        "Have the ability to speed up time",
        "Be constantly sticky",
        "Be loved by all",
        "Be able to make anyone fall asleep",
        "Have a personal driver",
        "Never have to eat",
        "Control water",
        "Be a villain with a cool costume",
        "Live under the sea",
        "Never need to charge your devices",
        "Speak to animals",
        "Be the best musician in the world",
        "Own a private jet",
        "Be able to fly at will",
        "Only be able to shout",
        "Be a famous singer",
        "Have no sense of smell",
        "Be able to control gravity",
        "Have an alien best friend",
        "Be 10 years younger",
        "Always have to dance instead of walk",
        "Have a pet dragon",
        "Live forever",
        "Have invisibility powers",
        "Only be able to wear wizard robes",
        "Be extremely smart",
        "Be able to mute people with your mind",
        "Live in a world with robots",
        "Have x-ray vision",
        "Be able to shapeshift",
        "Have the best dancing skills",
        "Own a time machine that only goes backward",
        "Be poor but travel the world",
        "Live in the sky",
        "Have the ability to stop time",
        "Have wings like a bird",
        "Have a teleporting bike",
        "Always be 10 minutes late",
        "Be the highest jumper in the world",
        "Have the ability to forget anything",
        "Be able to make it rain on command",
        "Be able to turn invisible forever but only once",
        "Always have snow wherever you go",
        "Be able to talk to plants",
        "Live in a spaceship",
        "Have a hoverboard",
        "Be the world's best baker",
        "Have unlimited free shoes",
        "Be able to enter others' dreams",
        "Have a closet that gives any outfit",
        "Have x-ray vision",
        "Have a flying car",
        "Always win at coin flips",
        "Be able to change your hair color at will",
        "Have a floating scooter",
        "Be able to make anything disappear",
        "Live on a luxury train forever",
        "Have a magic lamp with one wish",
        "Be able to erase others' embarrassing memories",
        "Have your own zoo",
        "Always have the newest car",
        "Be able to run super fast",
        "Have a loyal talking cat",
        "Be able to create ice blasts",
        "Be the best chess player in the world",
        "Have eyes that sparkle like stars",
        "Be able to grow to giant size",
        "Be a world-class dancer",
        "Have unlimited cotton candy",
        "Be able to wake up instantly refreshed",
        "Have a personal stylist",
        "Have rainbow-colored hair",
        "Have shoes that let you walk on water",
        "Be able to turn into any person",
        "Have a never-ending backpack of toys",
        "Have the ability to swap faces with anyone",
        "Live in a gingerbread house",
        "Have a snowman that never melts",
        "Be able to master any instrument instantly",
        "Have a car that flies",
        "Have your own private water park",
        "Be able to teleport but only within 1 mile",
        "Have glasses that see the future",
        "Always win at video games",
        "Have headphones that play your dreams",
        "Be able to pause any real-life conversation",
        "Have confetti hair",
        "Have a tiny robot army",
        "Have an unlimited supply of pizza",
        "Have a pillow that lets you control your dreams",
        "Have candy that gives you superpowers for 5 minutes",
        "Have hands that can heat things",
        "Have ears like an elephant",
        "Have a skateboard that flies",
        "Have a hat that makes it rain candy",
        "Be able to walk on rainbows",
        "Have a boat that flies",
        "Have a hoodie that plays music",
        "Have a phone that texts the future",
        "Have a clock that freezes time for 1 minute",
        "Have rollerblades that hover",
        "Have hair that styles itself",
        "Have a pet pegasus",
        "Have skin that sparkles like glitter",
        "Have socks that make money appear",
        "Have glasses that see through lies",
        "Have a fridge that dispenses desserts",
        "Have boots that let you bounce super high",
        "Have a flashlight that shows the past",
        "Have a blanket that makes you feel like you're in space",
        "Have music play whenever you walk",
        "Have a cloak that makes you invisible during the day",
        "Have a helmet that lets you breathe underwater",
        "Have shoes that float above the ground",
        "Have a wallet that gives you a coin every hour",
        "Have a sweater that changes colors with the weather",
        "Have a mirror that shows your ideal outfit",
        "Have gloves that turn anything into candy",
        "Have a hat that tells jokes",
        "Have a talking parrot",
        "Have a car that never runs out of fuel",
        "Have a house that changes rooms every day",
        "Have a backpack that produces pizza",
        "Have toothpaste that makes your breath smell like strawberries",
        "Have glasses that show people's favorite color",
        "Have headphones that let you hear thoughts",
        "Have a kite that flies itself",
        "Have a pen that writes jokes automatically",
        "Have a chair that flies",
        "Have a clock that tells the exact moment you'll laugh",
        "Have a diary that predicts tomorrow",
        "Have a scarf that makes you invisible during rain",
        "Have ice cream that tastes different every bite",
        "Have a butterfly the size of a dog",
        "Have a mirror that changes your outfit every hour"
    ]
};

function newQuestion(){
    const questionnum = Math.floor(Math.random() * questions.first.length);
    firstp.innerHTML = questions.first[questionnum]
    secondp.innerHTML = questions.second[questionnum]
    firstnum.innerHTML = redpicked
    secondnum.innerHTML = bluepicked
}

newQuestion()

div1.addEventListener("click", () => {
    redpicked += 1
    newQuestion()
})

div2.addEventListener("click", () => {
    bluepicked += 1
    newQuestion()
})